import './globals.css';
import '../assets/care-plus-admin-main.scss';
import { Inter } from 'next/font/google';
import LeftSideDrawer from '@/components/layout/layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LeftSideDrawer>{children}</LeftSideDrawer>
      </body>
    </html>
  );
}
